### ISSUE TITLE
Consider switching to new editor

### ISSUE THREAD

**Issue by animaux** [symphonists/editor_for_symphony#20]
https://github.com/lepture/editor says: NOTICE: @NextStepWebs has created an improved markdown editor based on this project

https://github.com/NextStepWebs/simplemde-markdown-editor/

**Comment by brendo** [comment]
Very nice. I love this editor, it's so clean and beautiful to use. WYSIWYG has definitely come a long way.

**Comment by nitriques** [comment]
Agreed :)

**Comment by animaux** [comment]
Switching to SimpleMDE plus making the buttons [configurable on a per-field-basis](https://github.com/symphonists/editor_for_symphony/issues/2#issuecomment-50936580) would make this extension a hot candidate for *symphony extension of the year 2016*. :)

**Comment by nitriques** [comment]
Ooo for sure !

**Comment by nathanhornby** [comment]
I came across this recently myself as well actually - great editor (I use the predecessor on my Symphony sites).

The **one** thing a markdown editor needs, that I've only seen in custom implementations (such as here on Github) is drag-and-drop inline images (or even any inline upload mechanism). There was talk a while back about achieving this using the Multi-upload field (I think?). Some clever JavaScript could probably bridge an editor and an upload field.

The person that makes that happen gets all the :cookie: :cookie:

**Comment by animaux** [comment]
@nathanhornby Hmm, I always prefer to have images not inline, but rather in galleries. Maybe this actually is because there is no such implentation yet :)

However it should actually be possible to process the images in the text-body to make use of JIT in the frontend. 

As a sidenote I have started to make use of [srcset|(http://caniuse.com/#search=srcset) recently. It’s playing very nicely with JIT and is very well supported nowadays. Jej!

**Comment by nitriques** [comment]
> The one thing a markdown editor needs, that I've only seen in custom implementations (such as here on Github) is drag-and-drop inline images (or even any inline upload mechanism)

Agreed. Youtube videos too..

**Comment by animaux** [comment]
—> https://github.com/animaux/simplemde

**Comment by twiro** [comment]
> _https://github.com/animaux/simplemde_

Hey... that comes in handy - just started a new project and considered switching to **simplemde** myself. So it's great to see a new extension released just when I need it... installed and looks good :) Thank you very much!

> _Switching to SimpleMDE plus making the buttons configurable on a per-field-basis would make this extension a hot candidate for symphony extension of the year 2016. :)_

Now regarding the extension of the year... I wouldn't want to have to configure the editor for each field I use it - instead something like "receipts" (the way we use them in JIT) for storing and attaching configuration-settings would be an awesome solution in my eyes. So if you or someone (or me) could give that a try this extension might truly become a candidate :)

And before you submit it to symphonyextensions.com - considered naming the repo "simplemde-markdown-editor"? Like the [original editor repo](https://github.com/NextStepWebs/simplemde-markdown-editor/)...? Would be simply more "human readable" which I think is always a plus for the ecosystem in the long run.

**Comment by animaux** [comment]
I’m not sure if it’s failsafe to use since I’m new to the business of creating extensions and learning by simply looking at what other people do.

At the moment the buttons are configured for my personal needs and what parts were working out of the box (fullscreen, side-by-side and other options would need some love). Not sure if I’m up to the task of making them configurable via field or general options. You idea of storable settings sounds nice, but I wont be able to do that, really. However it’s quite easy to configure the editor via the `simplemde.publish.js`.

You’re right about the name. I’ll see if I can fix this …

**Comment by twiro** [comment]
> _I’m not sure if it’s failsafe to use since I’m new to the business of creating extensions and learning by simply looking at what other people do._

No problem... it's just a small website and I will maintain most of the content myself. So perfect for testing and finding bugs! And I'm pretty new to the extensions-business too and am just learning things the same way you do ;)

> _Not sure if I’m up to the task of making them configurable via field or general options. You idea of storable settings sounds nice, but I wont be able to do that, really. However it’s quite easy to configure the editor via the simplemde.publish.js._

I wouldn't know how to do it either, but it might be an interesting challenge to find it out... someday ;)

**Comment by animaux** [comment]
Ok, thanks :)

The name is actually explanatory already: http://symphonyextensions.com/extensions/simplemde/

**Comment by nitriques** [comment]
Well done @animaux !

**Comment by animaux** [comment]
Thanks!
